name=LkgLib
version=0.76.0
author=Looking Glass Factory Ltd
maintainer=Looking Glass Factory Ltd
sentence=LGPL compliance.
paragraph=This library contains pre-compiled objects for STM32.
category=Device Control
url=https://lookingglassfactory.com/
architectures=stm32
dot_a_linkage=false
precompiled=true
